plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.16'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.qm'
version = '0.0.1-SNAPSHOT'
description = 'qm-admin-template'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

// 统一管理版本号，方便后续升级
ext {
    mapstructVersion = "1.5.5.Final"
    lombokMapstructBindingVersion = "0.2.0"
    mybatisPlusVersion = "3.5.11"
    springdocOpenapiVersion = "2.9.0"
    redissonVersion = "3.52.0"
}

dependencies {
    // Spring Boot 核心依赖
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // 参数校验
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation "org.redisson:redisson:${redissonVersion}"
    // security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // OpenAPI / Swagger UI
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocOpenapiVersion}"
    // MyBatis-Plus
    implementation "com.baomidou:mybatis-plus-spring-boot3-starter:${mybatisPlusVersion}"
    implementation "com.baomidou:mybatis-plus-jsqlparser:${mybatisPlusVersion}"
    //mysql
    runtimeOnly 'com.mysql:mysql-connector-j'
    // Lombok 依赖
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // MapStruct 核心依赖
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    // 协调 Lombok 和 MapStruct 的绑定依赖（关键）
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'com.h2database:h2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test') {
    useJUnitPlatform()
}
